version: "3.9"

services:
  backend:
    build: ./backend
    container_name: django_backend
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: vue_frontend
    volumes:
      - ./frontend:/app

    ports:
      - "5173:5173"
    command: npm run dev -- --host
