# Generated by Django 5.2.7 on 2025-10-02 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
        ('aviso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audios.audio'),
        ),
    ]
